### ISSUE TITLE
Default MDC context

### ISSUE THREAD

**Issue by edeak** [oshai/kotlin-logging#270]
The following test passes with version 2.1.23 and fails with version 3.0.4:

```kotlin
import kotlinx.coroutines.runBlocking
import mu.KotlinLogging
import org.junit.jupiter.api.Test

internal class MdcTest {
    @Test
    fun testMdcContextBehavior() = runBlocking {
        withContext(MDCContext(mapOf("foo" to "bar"))) {
            logger.warn { "context should have bar" }
            assertEquals(MDC.get("foo"}), "bar")

            awaitAll(
                async { assertMdcContext("bar1") },
                async { assertMdcContext("bar2") }
            )

            logger.warn { "context should have bar " }
            assertEquals(MDC.get("foo"), "bar")
        }
    }

    private suspend fun assertMdcContext(id: String) {
        withContext(MDCContext(mapOf("foo" to id))) {
            logger.warn { "message with $id" }
            assertEquals(MDC.get("foo"), id)
        }
    }
}
```

the failure happens because the underlying mdc adapter is `NOPMDCAdapter`

**Comment by oshai** [comment]
Thanks for the reproduction!
This looks like an issue with slf4j 1/2 compatibility. I am not sure what logging framework you're using but the bridge has to be replaced also.
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/2683969/217058808-bec51fb6-89c3-4f20-857c-b3c61887b619.png">
Foe example with log4j the jar should be changed from `log4j-slf4j-impl` to `log4j-slf4j2-impl`.
