### ISSUE TITLE
Upgrade to Gradle 8.0

### ISSUE THREAD

**Issue by yeikel** [oshai/kotlin-logging#288]
Creating a task to track this effort

https://docs.gradle.org/8.0/release-notes.html

@oshai Feel free to assign it to me :)

**Comment by oshai** [comment]
Contribution is welcome!

**Comment by oshai** [comment]
Created initial PR in #323

**Comment by severn-everett** [comment]
@oshai I've created a new PR for this task that will bring Gradle up-to-date along with some other dependency updates

**Comment by oshai** [comment]
Thanks!
