### ISSUE TITLE
[feature-request] support wasm target

### ISSUE THREAD

**Issue by VladislavSumin** [oshai/kotlin-logging#306]
It is possibly to support wasm target? Coroutines and Compose libraries already have experimental wasm target support

**Comment by oshai** [comment]
If you have any reference how to add such support to a lib I would be happy to add it. Of course contribution is also welcome.

**Comment by LaylaMeower** [comment]
> If you have any reference how to add such support to a lib

WASM is a compile target, that similarly to JS, has `browser` and `nodejs` - but it also has `d8` (no idea what that is tbh).

WASM Support will be very appreciated!

**Comment by oshai** [comment]
If I understand correctly, our current "native" implementation (writing logs using println) can also work in wasm. So the main thing to add is the gradle configuration. No need for many code changes.

**Comment by LaylaMeower** [comment]
Do note that when WASM is out of alpha, tit'll likely have interop with other WASM languages, allowing for usage of more complex log libraries than the basic stdout.

Plus, you can use JS `console` in WASM - it has JS interop.

**Comment by oshai** [comment]
Which impl do you think is the most appropriate?

**Comment by LaylaMeower** [comment]
> Which impl do you think is the most appropriate?

I think `console`, as it supports multiple log levels. *However*, `println` delegates to the standard WASM output. To allow a more more smooth interop with other languages when the time comes, I would suggest the option to have both, by making one the default and the other an add-on artifact (or making both an add-on artifact each)

The same, btw, applies to `println` - if you choose that, interop with JS will be less smooth.

(`console` supports, iirc, `debug`, `normal`/`info`, `warning`, and `error`, while `println` is only `normal`/`info` and `error`)

**Comment by gsteckman** [comment]
Kotlin for WebAssembly is now [alpha](https://blog.jetbrains.com/kotlin/2023/12/kotlin-for-webassembly-goes-alpha/).

**Comment by severn-everett** [comment]
What's left for this issue?

**Comment by oshai** [comment]
I am marking it as completed.
