### ISSUE TITLE
Support turning off logging in platforms other than the JVM

### ISSUE THREAD

**Issue by YarnSphere** [oshai/kotlin-logging#310]
I'm currently using version `4.0.0-beta-27`.

The current implementation seems to make it impossible to turn off logging in JS (and possibly all other platforms except JVM) since `KotlinLoggingConfiguration.LOG_LEVEL` is of type `Level` and there seems to be no way of configuring the logging level via integer.

I suggest the introduction of a new level: `Level.OFF`.

For reference, `sl4j-simple` provides an `OFF` level, defined as:

```java
// The OFF level can only be used in configuration files to disable logging.
// It has no printing method associated with it in o.s.Logger interface.
protected static final int LOG_LEVEL_OFF = LOG_LEVEL_ERROR + 10;
```

My current use-case for disabling logging is in unit testing. I wish to temporarily disable logging during certain tests so that I can test error scenarios without "polluting" the console. I'm working on a Kotlin multiplatform library and using `sl4j-simple` together with the default JS logger in unit testing.

**Comment by YarnSphere** [comment]
I can't promise, but if I have some time over the weekend, sure. Would you accept an implementation similar to `sl4j-simple`'s where we simply add a `Level.OFF` with a level of `50`?

Would it be enough to simply add this to the common `Level.kt` file? I'm not sure if something else would break from this addition and would have to manually check otherwise. I feel like you could probably add this feature much faster knowing the codebase and all, but if you also don't have the time I can probably take a stab at it.

**Comment by oshai** [comment]
Yes, let me know if you can get to it.
