### ISSUE TITLE
Add support for Android, iOS Native & Windows Native

### ISSUE THREAD

**Issue by LaylaMeower** [oshai/kotlin-logging#314]
I'm using this library for my WIP multiplatform game engine ([MoCKoGE](https://github.com/LaylaMeower/MoCKoGE/)) - I'm currently porting it to the multiplatform from JVM - and having Android, iOS & XBox  (through windows - as windows itself is supported by the JVM) support will be extremely nice.

**Comment by oshai** [comment]
In version 4 we have Android support, mingwX64 (windows),  and the following apple targets:
```
val darwinTargets = listOf(
        macosArm64(),
        macosX64(),
        iosArm64(),
        iosSimulatorArm64(),
        iosX64(),
        watchosArm64(),
        watchosSimulatorArm64(),
        watchosX64(),
        tvosArm64(),
        tvosSimulatorArm64(),
        tvosX64()
    )
```

**Comment by LaylaMeower** [comment]
> In version 4 we have Android support, mingwX64 (windows), and the following apple targets [...]

great, thanks! so using `common` only should "just work", right?

**Comment by Gaming32** [comment]
Where would I view my logs on the iOS Simulator?
