### ISSUE TITLE
Android default logging has changed in 4.0.0

### ISSUE THREAD

**Issue by benkuly** [oshai/kotlin-logging#327]
In kotiln-logging versions before 4.0.0 on Android slf4j was used for logging. This has been switched to `android.util.Log`.

Regarding to the [android documentation](https://source.android.com/docs/core/tests/debug/understanding-logging?hl=en), `java.util.logging` is used for "non-system application". As far as I know SLF4J does use it internally.

Maybe I missed something, but with `android.util.Log` there seems to be no reasonable configuration options for logging, which makes it unusable for us.

**Comment by oshai** [comment]
Releasing now 4.0.2 with a fix

**Comment by oshai** [comment]
To the best of my knowledge the default in android is `android.util.Log`.  
You can see popular frameworks like https://github.com/JakeWharton/timber that enhance it.
I think that traditionally (unlike servers) mobile devices want to keep away from debug logging for storage and performance reasons.

At the moment we will keep slf4j as the default, but I am still checking and in case it will be requested we might change the default in the future to native android logging. To use native logging set `-Dkotlin-logging-to-android-native=true`
