### ISSUE TITLE
update sample projects and docs

### ISSUE THREAD

**Issue by oshai** [oshai/kotlin-logging#337]
for all platforms and in https://github.com/oshai/kotlin-logging/wiki

**Comment by blackmo18** [comment]
Hi Would like to get update here.

It would be helpful to see how to use 5.01 version use with log4j, sl4j, logback examples

**Comment by oshai** [comment]
I updated https://github.com/MicroUtils/kotlin-logging-example-maven to version 5.

**Comment by oshai** [comment]
update the wiki.

**Comment by oshai** [comment]
updated android example to version 5 in https://github.com/MicroUtils/kotlin-logging-example-android (see readme)
