### ISSUE TITLE
Suspending function in curly brackets

### ISSUE THREAD

**Issue by recursive-rat4** [oshai/kotlin-logging#338]
I have a following code with version 4.0.1

```kotlin
suspend fun bar(): Int

suspend fun baz() {
    logger.info("Foo ${bar()}")
}
```

Now that version 5.0.0 deprecates round brackets, a straight conversion doesn't work, because it loses the suspension.

```kotlin
    logger.info { "Foo ${bar()}" }
    // e: Suspension functions can be called only within coroutine body
```

Would be a recommended way to wrap the suspending call into `runBlocking` like this?

```kotlin
    logger.info { "Foo ${runBlocking { bar() }}" }

**Comment by oshai** [comment]
I wouldn't use `runBlocking()` as it will block the thread.  
if you want it to work like before it should be translated to:
```
val barMessage = bar()
logger.info { "Foo $barMessage" }
```
(There is another question here which is why a log message computation will be a suspended operation).

**Comment by recursive-rat4** [comment]
>I wouldn't use runBlocking() as it will block the thread.

Thanks, I overlooked this detail.

>There is another question here which is why a log message computation will be a suspended operation

Mutexes, mutexes everywhere.

**Comment by ivan-osipov** [comment]
@oshai 
A practical problem that if you want to log extended context and load this data from your db, the method of loading is suspendable

so, for example, now you should do something like that
```kotlin
if(logger.isDebugEnabled()) { // or even trace
  val extraContext = loadMoreContext() // suspend func call
  logger.debug("Oops! Here is more context $extraContext")
}
```
instead of something like that
```kotlin
logger.coDebug { "Oops! Here is more context ${loadMoreContext()}" }
```
