### ISSUE TITLE
Payload not available to JS

### ISSUE THREAD

**Issue by robertfmurdock** [oshai/kotlin-logging#346]
ATM, the "formatter" interfaces only receive the message, which makes it impossible to fold in any structured information from the payload.

This prevents using the payload as a meaningful structure in a multiplatform logging sense, as only some platforms will be able to access it 😭

**Comment by oshai** [comment]
We can pass the payload to the formatter... how do you think such api should look like?

**Comment by robertfmurdock** [comment]
I imagine passing it down alongside the message would be sufficient

**Comment by oshai** [comment]
Something like this: https://github.com/oshai/kotlin-logging/pull/347 ?

**Comment by robertfmurdock** [comment]
Makes sense to me. Would it make sense for the message to be passed through as the simple string then instead of the function arg? Or both of them be passed as function args? It seems slightly inconsistent for one to be a function producer and the other a flat map, but if there's an underlying mechanical reason that'd be fine

**Comment by oshai** [comment]
Thanks, I am planning to make a bit bigger change by having a shared module for both native and js (non delegating platforms), so I will add it as part of that.

**Comment by oshai** [comment]
@robertfmurdock see the planned changes in https://github.com/oshai/kotlin-logging/pull/350

**Comment by oshai** [comment]
Fixed in https://github.com/oshai/kotlin-logging/pull/350
