### ISSUE TITLE
Gradle logging

### ISSUE THREAD

**Issue by jpink** [oshai/kotlin-logging#352]
I want to use KotlinLogging in Gradle Plugin. How to route logging messages to Gradle Logging API? Probably using SLF4J?

You can create Logger using `org.gradle.api.logging.Logging.getLogger(my.Plugin::class.java)` or you can use `project.logger` property directly.

**Comment by oshai** [comment]
According to docs:

> Gradle routes all logging via SLF4J. You can use either an SLF4J Logger or a Gradle [Logger](https://docs.gradle.org/current/javadoc/org/gradle/api/logging/Logger.html) to perform logging.

https://docs.gradle.org/current/javadoc/org/gradle/api/logging/Logging.html

So I think using slf4j module (regular jvm) should work.
