### ISSUE TITLE
setting logging level per KLogger instance in run-time 

### ISSUE THREAD

**Issue by vak** [oshai/kotlin-logging#369]
Q: is it possible to set the logging level in a run-time **not** [globally](https://github.com/oshai/kotlin-logging/wiki#q-how-do-i-set-the-log-level), but per KLogger-instance? 

Ideally it should be agnostic of underlying logging framework. That is, it would be ideally done within this `kotlin-logging` library via some setLogLevel member function.

This would be extremely useful for enabling individual log-levels for different modules, class instances, etc. 

Unfortunately, logging is a deep ocean, we'd be happy to swim across it without sinking in underlying logging frameworks :-)

**Comment by oshai** [comment]
Thanks for raising the issue. I don't think I have a good answer ready for you, but I will write few thoughts.
The lib started as a facade for JVM and as such it delegates everything to the underlying (slf4j) framework. In jvm, not all frameworks support dynamically change of level.
Now in multi-platform it somehow makes sense as the lib act as a low level lib (not facade). It mostly makes sense for platforms inherit from [direct](https://github.com/oshai/kotlin-logging/blob/master/src/directMain/kotlin/io/github/oshai/kotlinlogging/internal/KLoggerDirect.kt). I am not sure what platform you had in mind, but we can continue the discussion from there.

**Comment by vak** [comment]
@oshai, thank you for responding. I am using Kotlin on a daily basis for 1 year only and am still quite shallow on JVM ecosystem. Therefore I asked my colleagues for help on this part :-)

However, my naive hope is that such setLogLevel() function should either set the log level if it is supported by underlying logging framework _or_ it should just spit an error once "can't set logging level for ..."  without any effect if the underlying logging framework doesn't support this.

**Comment by oshai** [comment]
You can see some more details how to do it in [here](https://github.com/oshai/kotlin-logging/wiki#q-how-do-i-set-the-log-level). Right now I don't have any plans to add it to the lib.
