### ISSUE TITLE
Publish Dokka HTML docs on project site

### ISSUE THREAD

**Issue by EdricChan03** [oshai/kotlin-logging#382]
I've noticed that the project uses [Dokka](https://kotlinlang.org/docs/dokka-introduction.html), but there doesn't appear to be a [HTML version](https://kotlinlang.org/docs/dokka-html.html) of the API docs published anywhere on [this project's GitHub Pages site](https://oshai.github.io/kotlin-logging/) - are there plans to do so?

Some quick sleuthing does show that it's published as part of the artifact's Javadoc, [where the HTML docs can be found](https://javadoc.io/doc/io.github.oshai/kotlin-logging-jvm/latest/index.html) :eyes:

**Comment by oshai** [comment]
Do you know how to configure that upload?
