### ISSUE TITLE
KLoggingEventBuilder accept nullable values in payload

### ISSUE THREAD

**Issue by Zack-Freedman-Thoughtworks** [oshai/kotlin-logging#400]
Hello! Is it possible to modify KLoggingEventBuilder to accept nullable values? This would allow us to avoid null-checks in the code we are adding logs to. 

Example:
```Kotlin
logger.atError {
    this.message = "Failed to make a good example: ${throwable.message}."
    this.cause = throwable
    this.payload = mapOf(
        "itemOne" to headers.getNullableThing(),
    )
}
```

**Comment by oshai** [comment]
yes. would you like to create a PR?

**Comment by Zack-Freedman-Thoughtworks** [comment]
@oshai Created a PR [here](https://github.com/oshai/kotlin-logging/pull/402). Would you please help me validate that it doesn't lead to a null-pointer? I'm not too knowledgable in how this library integrates with the other libraries as a whole. 

Sadly as these are public classes, I'm not sure if these are backwards compatible changes. I also happen to know data classes don't fair well with backwards compatible changes either. See [here](https://kotlinlang.org/docs/jvm-api-guidelines-backward-compatibility.html)

**Comment by oshai** [comment]
I think the change is safe (both NPE and backward compatibility).
