### ISSUE TITLE
Wrong class name printed when using LoggingEventBuilder with payload

### ISSUE THREAD

**Issue by MzrW** [oshai/kotlin-logging#416]
The wrong class name is printed when using the LoggingEventBuilder with a payload.

The following example demonstrates the issue:
``` kotlin
package my.pkg

import io.github.oshai.kotlinlogging.KotlinLogging

private val logger = KotlinLogging.logger {  }

fun main() {
    logger.atInfo {
        message = "hi"
        payload = mapOf("k" to "v")
    }

    logger.atInfo {
        message = "hi"
    }
}
```

Which will print:
``` txt
Apr. 06, 2024 4:49:02 AM io.github.oshai.kotlinlogging.slf4j.internal.LocationAwareKLogger logWithPayload
INFORMATION: k=v hi
Apr. 06, 2024 4:49:02 AM my.pkg.MyClassKt main
INFORMATION: hi
```

The first log statement will be logged with `io.github.oshai.kotlinlogging.slf4j.internal.LocationAwareKLogger` as a classname.
Which is wrong. It supposed to be `my.pkg.MyClassKt`.

In the second log statement however it seems to work fine.

Check out the example to reproduce the issue: [example.zip](https://github.com/oshai/kotlin-logging/files/14892145/example.zip)

**Comment by MzrW** [comment]
The difference seems to be inside `LocationAwareKLogger`.

Log statements without payload are logged using: `org.slf4j.spi.LocationAwareLogger.log(org.slf4j.Marker marker, String fqcn, int level, String message, Object[] argArray, Throwable t)`

Log statements with payload are logged using:
`org.slf4j.spi.LoggingEventBuilder.log(String message)`.
LocationAwareKLoggger.logWithPayload seems to correctly set the callerBoundary.

The first thing `org.slf4j.spi.DefaultLoggingEventBuilder.log(String message)` does is to override the callerBoundary with its own classname.

Therefore I think the bug is inside slf4j not in kotlin-logging.

Maybe leave the issue open until the bug is resolved there ...

**Comment by oshai** [comment]
Are you using log4j? There was a related bug there.

**Comment by MzrW** [comment]
No Im using slf4j-jdk the java util logging.

**Comment by oshai** [comment]
Log4j slf4j issue is here for reference: https://github.com/apache/logging-log4j2/issues/1533

**Comment by oshai** [comment]
It might be a similar fix.

**Comment by oshai** [comment]
Seems like this should be fixed in slf4j 2.0.13. I will try to upgrade.

**Comment by oshai** [comment]
> Seems like this should be fixed in slf4j 2.0.13. I will try to upgrade.

should be in version 6.0.9.

**Comment by MzrW** [comment]
When using slf4j version 2.0.13 the correct class name is logged.
@oshai feel free to close the issue.

**Comment by oshai** [comment]
Thanks!
