### ISSUE TITLE
Obtaining a Logger documentation outdated

### ISSUE THREAD

**Issue by mixomat** [oshai/kotlin-logging#456]
As the "old" way of obtaining a `KLogger` instance via a companion object is now deprecated, the Wiki documentation is now outdated and leads to confusion:

https://github.com/oshai/kotlin-logging/wiki#obtaining-a-logger

Deprecation: https://github.com/oshai/kotlin-logging/blob/1f9ecdddc7cc43a03193b431866e7c243491a8d1/src/jvmMain/kotlin/io/github/oshai/kotlinlogging/KLogging.kt#L16

**Comment by mixomat** [comment]
I think it would make sense, to explicitly mark the companion object way as deprecated (or remove it from the documentation).

**Comment by oshai** [comment]
Thanks! I removed it from docs.

Let me know if you find anything else that would help.
